import matplotlib.pyplot as plt
import numpy as np
sizes = np.array([500, 1000, 2000, 4000])
times = np.array([7.11e-05, 0.0002563, 0.0009663, 0.0037335])
fig, axes = plt.subplots(1, 2, figsize=(13, 5))
axes[0].plot(sizes, times, '^-', color='tab:red', linewidth=2, markersize=7, label='C++ (Selection Sort)')
axes[0].set_title(r'Đồ thị thời gian $T(n)$ theo $n$ (C++)', fontsize=12, fontweight='bold')
axes[0].set_xlabel('Kích thước mảng (n)', fontsize=11)
axes[0].set_ylabel('Thời gian thực thi (giây)', fontsize=11)
axes[0].set_xticks(sizes)
axes[0].grid(True, linestyle='--', alpha=0.6)
axes[0].legend(fontsize=10)
for x, y in zip(sizes, times):
    axes[0].annotate(f'{y:.6f}s', (x, y), textcoords='offset points', xytext=(0, 8), ha='center', fontsize=9)
axes[1].plot(sizes, times, 's-', color='tab:red', linewidth=2, markersize=7, label='C++ (Log-Log)')
axes[1].set_xscale('log')
axes[1].set_yscale('log')
axes[1].set_title(r'Đồ thị thang Log-Log ($log T$ theo $log n$)', fontsize=12, fontweight='bold')
axes[1].set_xlabel('Kích thước mảng n (thang log)', fontsize=11)
axes[1].set_ylabel('Thời gian thực thi T (thang log)', fontsize=11)
axes[1].set_xticks(sizes)
axes[1].get_xaxis().set_major_formatter(plt.ScalarFormatter())
axes[1].grid(True, which='both', linestyle='--', alpha=0.6)
axes[1].legend(fontsize=10)
slope, _ = np.polyfit(np.log(sizes), np.log(times), 1)
axes[1].text(0.05, 0.85, f'Hệ số góc (Slope) ≈ {slope:.2f}', transform=axes[1].transAxes, fontsize=10, bbox=dict(boxstyle='round,pad=0.3', fc='yellow', alpha=0.3))
plt.tight_layout()
plt.savefig('dothi_bai44_cpp.png', dpi=300)
